# Git aliases (platform-independent)

alias g='git'
alias gs='git status'
alias ga='git add .'
alias gp='git push'
alias gl='git log'
alias gd='git diff'
alias gm='git commit -m'
alias gma='git commit -am'
alias gb='git branch'
alias gc='git checkout'
alias gra='git remote add'
alias grr='git remote rm'
alias gpu='git pull'
alias gcl='git clone'
alias gta='git tag -a -m'
alias gf='git reflog'
alias glt='git ls-tree --full-tree -r HEAD'
alias gr='git rm $(git ls-files --deleted)'
